# Development Procfile
# Author @0xADADA


# The webserver: Python
webserver: cd app && ./manage.py runserver_plus 0.0.0.0:8080

# The CDN assets emulation server
cdnserver: cd /var/app/app/dist && python -m http.server 8010
